### ISSUE TITLE
Adding an optional webhook endpoint

### ISSUE THREAD

**Issue by aleixmorgadas** [dgarcia360/nem2-uri-scheme#2]
I have a case where I'm not able to track the transaction handled by uri schema due to no user context. Since the transaction hash includes the signer public key, I have no way, without asking the user to "login with account address", to know which is the transaction the app should track.

The proposal is adding another parameter to the uri-schema with a server endpoint, I'm thinking on

`...&webhook=https://<url>` 

Or similar.

What do you think? I could make a PR with this change if you think it's a good way to go.

**Comment by dgarcia360** [comment]
Thanks for opening an issue, the secure environment (e.g. wallet)  announcing the transaction definitely needs to callback the application so that it can monitor the transaction status.

I would really appreciate it if you can open the pull-request adding the ``webhook`` field.

Note as well that webhooks **POST**  **data** to the URL specified. That means we need to describe as well the response the secure environment has to send, so it's standardized between wallets. An initial specification could be:

**Prerequisite** 
The webhook URL must identify the transaction and user uniquely. Example: https://webhook.appurl.com/<transaction_id>

**AnnounceTransaction Response**
```
{
   "action": "AnnounceTransaction",
   "data": {
       "hash":  "string
       "signer":"string", //publicKey
   }
}
```

Let me know if you need anything else after testing the workflow with the app you are developing.

**Comment by aleixmorgadas** [comment]
> I would really appreciate it if you can open the pull-request adding the webhook parameter.

Yes, I will do! ^^

> __Prerequisite__
> 
> The webhook URL must identify the transaction and user uniquely. Example: 
> https://webhook.appurl.com/<transaction_id>

I would suggest instead of `transactionID`, be a `correlationID` defined by the service. A `correlationID` can or cannot be a `transaction hash`.

The motivation of defining it as [`correlationID`](https://www.enterpriseintegrationpatterns.com/patterns/messaging/CorrelationIdentifier.html) is that the server can track better all the transaction flow going though different systems.

If the URL Schema has `webook` defined, it does not require a `correlationID`. Instead, the wallet that implements the feature should act as it is just an endpoint to send the `POST data`.

Some valid webhooks URLs:

- http://randomsite.extension/webhook
- https:///randomsite.extension/webhook
- https:///randomsite.extension/webhook/107386E0-1AA5-4EF7-AE5B-5063D11558F6
- https:///randomsite.extension/webhook/84324b066eb752078af86b0a44d117132c46170f431c0b06598c3c42309bbb66

> __AnnounceTransaction Response__
>
>```json
>{
>   "action": "AnnounceTransaction",
>   "data": {
>       "hash":  "string
>       "signer":"string", //publicKey
>   }
>}
>```

I undestand that _AnnounceTransaction Response_ is the body send to the webhook. If so, I think it's OK for first iteration, I don't see any important information missing.

**Comment by dgarcia360** [comment]
Agree, when I was referring to ``transactionID`` I was referring to ``correlationID `` :+1:

**Comment by evias** [comment]
This would not allow such webhooks:

`https://random.site/endpoint?param=value&param2=value` 

Because the transaction URI is to provide query parameters format already. Am I right?

Can we add url encoding to overcome this problem and also allow such URLs ? I find it limiting as we can still see many web software using this.

**Comment by dgarcia360** [comment]
@evias It is possible to POST to any URL given - including URLs with params. A separate discussion would be if, from an API design perspective,  adding query parameters to a POST URL is a good idea o not.

The application dev does not define the body sent to the webhook through the URL, it's given.  The webhook receives what the wallet POSTS in the format described previously to the URL specified.

The `correlationId``, or any group of parameters that describe the uniqueness of the action, can be appended as path parameters, which is a common practice when sending POST requests.

**Comment by evias** [comment]
thanks for clarifying :+1:

**Comment by dgarcia360** [comment]
PR merged, will close the issue once I edit the NIP.
